topics <- tribble(
  ~category, ~topic,
  "d1", "Gender",
  "c1", "Age",
  "d2", "Occupation",
  "c4", "Education",
  "c5", "Place size",
  "c16", "Cooling system",
  "c17", "Cooling system usage",
  "c18", "Heating system",
  "c19", "Heating system configuration",
  "c20", "Heating system usage",
  "c21", "Energy items",
  "c22", "Heating costs",
  "c23", "Heating costs - accuracy",
  "c24", "Hot water costs",
  "c25", "Hot water costs - accuracy",
  "c26", "Energy costs",
  "c27", "Energy costs - accuracy",
  "c28_1", "Energy poverty - ability to pay",
  "c28_2", "Energy poverty - threats",
  "c28_3", "Energy poverty - safety in winter",
  "c28_4", "Energy poverty - safety in summer",
  "c29", "Housing type",
  "c30", "Housing area",
  "c31", "Housing age",
  "c32", "Major renovations",
  "c33", "Energy Performance Certificates",
  "c34", "Energy rating",
  "c35", "Number of cars",
  "c36", "Modes of transport",
  "c37", "Plane travel",
  "c38", "Frequency of plane travel",
  "c39_1", "Neighborhood - Trust",
  "c39_2", "Neighborhood - Mistrust",
  "c39_3", "Neighborhood - Willingness to help",
  "c39_4", "Neighborhood - Friendliness",
  "c39_5", "Neighborhood - Community spirit",
  "c39_6", "Neighborhood - Community support",
  "c39_7", "Neighborhood - Respect",
  "c39_8", "Neighborhood - Tolerance",
  "c39_9", "Neighborhood - Belonging",
  "c40", "Support for policy",
  "c41", "Support for Citizens' Assemblies",
  "c42", "Fairness of decision making",
  "c43", "Acceptance of decision making",
  "c44_1", "Identity - environmentally friendly consumer",
  "c44_2", "Identity - concerned with environment",
  "c44_3", "Identity - environmental behavior 1",
  "c44_4", "---",
  "c44_5", "Identity - environmental behavior 2",
  "c45_1", "Energy transition - No knowledge",
  "c45_2", "Energy transition - Rejection",
  "c45_3", "Energy transition - Little contribution",
  "c45_4", "Energy transition - Much contribution",
  "c46_1", "Energy activities - Saving energy",
  "c46_2", "Energy activities - Tracking energy consumption",
  "c46_3", "Energy activities - Talking with others",
  "c46_4", "Energy activities - Engaging in local projects",
  "c46_5", "Energy activities - Demonstrating",
  "c46_6", "Energy activities - Joining an energy cooperative",
  "c47_1", "Institutional trust - EU",
  "c47_2", "Institutional trust - National politicians",
  "c47_3", "Institutional trust - Regional politicians",
  "c47_4", "Institutional trust - Local politicians",
  "c47_5", "Institutional trust - National agencies",
  "c47_6", "Institutional trust - Legal system",
  "c47_7", "Institutional trust - Scientists",
  "c47_8", "Institutional trust - Industry",
  "c47_9", "Institutional trust - Public media",
  "c48_1", "Adults in the household",
  "c48_2", "Children in the household",
  "c49", "Tenant or owner?",
  "c50", "Cost of living",
  "c51", "Impairments in living",
  "c52", "Household occupancy",
  "c53", "Stable income",
  "c54", "Income description",
  "c55", "Income",
  "c56_1", "Political identity - national policies",
  "c56_2", "Political identity - social policies",
  "c56_3", "Political identity - conservative policies",
  "c56_4", "Political identity - liberal policies",
  "c56_5", "Political identity - environmental policies",
  "c57", "Cooperative self-generation",
  "c58", "Future cooperative self-generation",
  "c59", "Severity of effects from fossil fuel energy",
  "c60", "Time of effects from fossil fuel energy",
  "c61", "Personal effects from cooperative self-generation",
  "c62", "Support for cooperative self-generation",
  "c63", "Knowledge and resources for cooperative self-generation",
  "c64", "Relation to businesses on self-generation - currently",
  "c65", "Relation to businesses on self-generation - optimally",
  "c66", "Relation to government on self-generation - currently",
  "c67", "Relation to government on self-generation - optimally",
  "c68", "Feelings towards cooperative self-generation",
  "c69", "Use of ustainable transport",
  "c70", "Future use of sustainable transport",
  "c71", "Severity of effects from unsustainable transport",
  "c72", "Time of effects from unsustainable transport",
  "c73", "Personal effects from sustainable transport",
  "c74", "Support for sustainable transport",
  "c75", "Knowledge and resources for sustainable transport",
  "c76", "Relation to businesses on sustainable transport - currently",
  "c77", "Relation to businesses on sustainable transport - optimally",
  "c78", "Relation to government on sustainable transport - currently",
  "c79", "Relation to government on sustainable transport - optimally",
  "c80", "Feelings towards sustainable transport",
  "c81", "Use of electric vehicles",
  "c82", "Future use of electric vehicles",
  "c83", "Severity of effects from gasoline and diesel",
  "c84", "Time of effects from gasoline and diesel",
  "c85", "Personal effects from electric vehicles",
  "c86", "Support for electric vehicles",
  "c87", "Knowledge and resources for electric vehicles",
  "c88", "Relation to businesses on electric vehicles - currently",
  "c89", "Relation to businesses on electric vehicles - optimally",
  "c90", "Relation to government on electric vehicles - currently",
  "c91", "Relation to government on electric vehicles - optimally",
  "c92", "Feelings towards electric vehicles",
  "c93", "Use of gas in appliances",
  "c94", "Future use of gas in appliances",
  "c95", "Severity of effects from gas in appliances",
  "c96", "Time of effects from gas in appliances",
  "c97", "Personal effects from replacing gas in appliances",
  "c98", "Support for replacement of gas in appliances",
  "c99", "Knowledge and resources for replacing gas in appliances",
  "c100", "Relation to businesses on gas in appliances - currently",
  "c101", "Relation to businesses on gas in appliances - optimally",
  "c102", "Relation to government on gas in appliances - currently",
  "c103", "Relation to government on gas in appliances - optimally",
  "c104", "Feelings towards replacing gas in appliances",
  "c6_1", "Energy activities - Unplug unused devices",
  "c6_2", "Energy activities - Search for energy-efficient products",
  "c6_3", "Energy activities - Turn off lighs",
  "c6_4", "Energy activities - Encourage friends and family",
  "c6_5", "Energy activities - Participate in carpooling",
  "c6_6", "Energy activities - Travel without a car",
  "c7", "Energy information sources",
  "c8", "Trust for energy information sources",
  "c9", "Social media and energy information",
  "c10", "Topics for energy information",
  "c11_1", "Topic complexity - Electricity consumption",
  "c11_2", "Topic complexity - Heating/cooling consumption",
  "c11_3", "Topic complexity - Energy spending",
  "c11_4", "Topic complexity - Share of renewables",
  "c11_5", "Topic complexity - Implementing green solutions",
  "c12", "National energy development",
  "c13_1", "Energy saving - Lower water temperature",
  "c13_2", "Energy saving - Shorter showers",
  "c13_3", "Energy saving - Drive slower",
  "c13_4", "Energy saving - Full dishwasher",
  "c13_5", "Energy saving - Use public transport",
  "c14_1", "Attitude - Importance of energy efficiency",
  "c14_2", "Attitude - Concern for energy use",
  "c14_3", "Attitude - Inconvenience",
  "c14_4", "Attitude - Energy behavior",
  "c14_5", "Attitude - Ability to conserve energy",
  "c14_6", "Attitude - Positive impact",
  "c14_7", "Attitude - Comfort",
  "c14_8", "Attitude - Conservation",
  "c14_9", "Attitude - National economy",
  "c14_10", "Attitude - Moral obligation",
  "c14_11", "Attitude - Different views",
  "c14_12", "Attitude - Personal finances",
  "c15_1", "Attitude - Need for renewables",
  "c15_2", "Attitude - Role of government",
  "c15_3", "Attitude - climate change",
  "c15_4", "Attitude - Local and national energy issues",
  "c15_5", "Attitude - Participation",
  "c15_6", "Attitude - Energy affordability",
  "c15_7", "Attitude - Energy independence",
  "c15_8", "Attitude - Energy independence 2",
  "c15_9", "Attitude - Energy sources",
  "c15_10", "Attitude - Energy justice"
)

# Energy literacy
# Energy efficiency and buildings
# Demographics
# Social cohesion
# Three-stage model